name: Metrics

on:
  # Hourly refresh
  schedule:
    - cron: "0 * * * *"
  # Manual dispatch and on every commit
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # ---------- LEFT PANEL ----------
      - name: left
        uses: stalomeow/metrics@projects-v2
        with:
          # Auth token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Core options
          user: Michael-OvO
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          repositories_affiliations: owner

          # Follow-up section
          plugin_followup: yes
          plugin_followup_sections: user

          # Language stats
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_ignored: jupyter notebook

          # Commit attribution
          commits_authoring: Michael-OvO

          # Stargazers & people graphs
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: chartist
          plugin_people: yes
          plugin_people_limit: 100
          plugin_people_types: followers,following

          # Display order
          config_order: followup, languages, stargazers

      # ---------- RIGHT PANEL ----------
      - name: right
        uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Core options
          user: Michael-OvO
          template: classic
          base: ""
          config_timezone: Asia/Shanghai

          # Achievements
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: D
          plugin_achievements_display: detailed
          plugin_achievements_limit: 0
          plugin_achievements_ignored: projects
